services:
  mpd:
    build:
     context: .
     dockerfile: Dockerfile
    image: ghcr.io/mishka81/alpine-mpd:latest
    container_name: mpd
    ports:
      - "6600:6600"
      - "8000:8000"
#    devices:
#      - /dev/snd
    volumes:
      - ${MUSIC_FOLDER}:/var/lib/mpd/music:ro
      - ${PLAYLISTS_FOLDER}:/var/lib/mpd/playlists
      - ./mpd.conf:/etc/mpd.conf:ro
    restart: unless-stopped